FROM lighty262/afs:1.0

WORKDIR /app

COPY rootfs/ /

RUN chmod +x /usr/bin/skiddph-dev  \
    && chmod +x /usr/bin/skiddph-daemon \
    && chmod +x /usr/bin/skiddph-ws

# Include port 9000 if Websocket is enabled
EXPOSE 80 3000
ENTRYPOINT ["/usr/bin/skiddph-dev"]
