#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/html/autoload.php')) {
    require_once __DIR__ . '/html/autoload.php';
} else if (file_exists(__DIR__ . '/autoload.php')) {
    require_once __DIR__ . '/autoload.php';
} else if (file_exists('/app/autoload.php')) {
    require_once '/app/autoload.php';
} else {
    die('Autoload not found');
}

echo "[Test] Loaded extensions: ", count(get_loaded_extensions()), PHP_EOL;

$test_scripts = [
    ['test_mc'],
    ['test_db'],
];

foreach ($test_scripts as $args) echo cmd($args);
echo "[Test] Done", PHP_EOL;
