#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/html/autoload.php')) {
    require_once __DIR__ . '/html/autoload.php';
} else if (file_exists(__DIR__ . '/autoload.php')) {
    require_once __DIR__ . '/autoload.php';
} else if (file_exists('/app/autoload.php')) {
    require_once '/app/autoload.php';
} else {
    die('Autoload not found');
}

if (!isset($argv[1]) || empty($argv[1])) {
    echo ('No model name given');
    exit(1);
}

echo cmd(['model_make', $argv[1]]);
