#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/html/autoload.php')) {
    require_once __DIR__ . '/html/autoload.php';
} else if (file_exists(__DIR__ . '/autoload.php')) {
    require_once __DIR__ . '/autoload.php';
} else if (file_exists('/app/autoload.php')) {
    require_once '/app/autoload.php';
} else {
    die('Autoload not found');
}

$address = env('WS_HOST_ADDR');
$port = env('WS_HOST_PORT');

$socket = new App\Controller\WebSocket($address, $port);
$socket->run();