#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/html/autoload.php')) {
    require_once __DIR__ . '/html/autoload.php';
} else if (file_exists(__DIR__ . '/autoload.php')) {
    require_once __DIR__ . '/autoload.php';
} else if (file_exists('/app/autoload.php')) {
    require_once '/app/autoload.php';
} else {
    die('Autoload not found');
}

$address = '127.0.0.1';
$port = 8081;

$socket = new App\Controller\WebSocket($address, $port);
$socket->run();